### ISSUE TITLE
小白不太懂 这个问题要怎么处理呀

### ISSUE THREAD

**Issue by hantiany** [wangtao2213405054/subscribe-subway#1]
![image](https://user-images.githubusercontent.com/48743184/226533218-ba5813fd-a48b-4d0c-8fda-56e2723b48fe.png)

**Comment by hantiany** [comment]
解决了  没有安装 setuptools

**Comment by wangtao2213405054** [comment]
在刚刚提交的 commit 里面做了一些说明，可以重新 clone 一下代码，更新了readme文档及环境依赖等

**Comment by hantiany** [comment]
![image](https://user-images.githubusercontent.com/48743184/226539177-ca723495-4361-4eaf-979f-263f3f5c7e91.png)

**Comment by wangtao2213405054** [comment]
> ![图像](https://user-images.githubusercontent.com/48743184/226539177-ca723495-4361-4eaf-979f-263f3f5c7e91.png)
可否把配置文件的信息发来让我看一下，或者你可以使用最新版本的代码来规避这个问题。
看问题是发送钉钉的机器人消息时出现的问题。

**Comment by hantiany** [comment]
```json
{
  "dingTalkToken": "https://oapi.dingtalk.com/robot/send?access_token=93b1b5b055553d16cb1061da8c631c6fbfbe426a1844b664ad21dd92bab5570b",
  "dingTalkSign": "SEC7cb54a342dabb03ea065f2183ebd5916db93b2da55fb62e0726fb83e6f3427be",
  "UserAgent": [
    {
      "lineName": "昌平线",
      "stationName": "沙河站",
      "timeSlot": "0820-0930",
      "name": "十二",
      "mobile": "18888888888",
      "token": "Mjk3ZGFiMjYtYTA0Yy00MWE3LTk4NTYtZDAyMjk4MjhhNDdmLDE2ODAwMjMzNjE0NDUsV0VEM1UzbDIweEkwVTNhSDlXcU5LTkdSR05JPQ=="
    }
  ]
}
```

**Comment by wangtao2213405054** [comment]
请尝试一下将 message.py 文件中的第39行 def sign(secret) -> tuple[str, str]: 中的  -> tuple[str, str] 代码删除, 由于我的 python 版本是3.9的，无法复现此问题-.-

**Comment by hantiany** [comment]
![image](https://user-images.githubusercontent.com/48743184/226541980-c1d471c8-a872-4286-b5d4-a286d1a48c8f.png)

**Comment by wangtao2213405054** [comment]
将``` -> tuple[str, str]``` 这部分删除掉就可以了

**Comment by wangtao2213405054** [comment]
```def sign(secret) -> tuple[str, str]:``` 改为 ```def sign(secret):``` 即可

**Comment by hantiany** [comment]
改了subscribe-subway/subway/message.py 不生效
还是从 /usr/local/lib/python3.6/site-packages/subscribe_subway_capital-1.0.0-py3.6.egg/subway/message.py 读取的

**Comment by wangtao2213405054** [comment]
> 

我还在配置文件之中发现了一个其他的问题, "timeSlot": "0820-0930", 这个时段太久了, 地铁预约时段应该是 10 分钟 0820-0830

**Comment by hantiany** [comment]
> > 
> 
> 我还在配置文件中发现了一个其他的问题, "timeSlot": "0820-0930", 这个时间段太久了, 地铁预约时间段应该是10分钟0820-0830

这个支持 多段时间预约吗

**Comment by wangtao2213405054** [comment]
> 
我大概知道你的问题了， 你需要进入`/usr/local/lib/python3.6/site-packages` 目录将`subscribe_subway_capital-1.0.0-py3.6.egg` 文件夹整体删除掉 mac 系统你可以通过 Commad + Shift + G 来进入指定的目录之中

**Comment by wangtao2213405054** [comment]
> 

目前还是不支持的，不过有时间的话我可以去做一下，现在的话你可以在 UserAgent 中添加多个一致的用户，但是时段不同即可

**Comment by hantiany** [comment]
> 

删除了就 `No module named 'subway'`

**Comment by wangtao2213405054** [comment]
> 

你方便我帮你远程一下吗，这可能是你的 python 环境的问题

**Comment by wangtao2213405054** [comment]
Q：2213405054

**Comment by wangtao2213405054** [comment]
此问题为 Python 版本过低，修改了Python 环境依赖为3.9 readme 文档同步更新
